### ISSUE TITLE
Upgrade View.

### ISSUE THREAD

**Issue by TJTeta1** [MTStrot/Wind-Overlay#48]
When looking at the VT SCADA if we could view what turbine faults instead of Unavailable, I think that would be more helpful.
![vt scada](https://user-images.githubusercontent.com/34145120/40585136-d4a1559c-619c-11e8-9442-5a6bd10a2b21.png)

For example how the GE SCADA shows what turbine is faulted. I know if you click on the VT SCADA site name it will show more information similar to GE SCADA but having it all on that one page would make things similar to what we are looking at now.

![vt scada 2](https://user-images.githubusercontent.com/34145120/40585159-498ddb1e-619d-11e8-89e8-77a4e4f1c27a.png)

**Comment by MTStrot** [comment]
This was added a while back.
