### ISSUE TITLE
NCSSII

### ISSUE THREAD

**Issue by susanbruno** [MTStrot/Wind-Overlay#62]
We need the Gen Data.
--

**Comment by MTStrot** [comment]
This was added

**Comment by susanbruno** [comment]
Thanks for all the fixes Michael. When I looked for the Generator on NCSSII in the new SCADA, I am not sure under which heading we would see it. Maybe Power? And unfortunately, when I looked, the Meter was stale/No comms- see pic. - Might just be due to end of day irradiance as I saw it go to zero MW a couple times, each inverter showed like 5 kW when it did that. Its all zeros and back to 23.58 MW now. I will try to catch it earlier tomorrow, Im nights this week.
![2020-02-05_16-47-16](https://user-images.githubusercontent.com/33696093/73886725-225b5200-4838-11ea-8da4-4f62c489c64b.png)

**Comment by MTStrot** [comment]
You can see the Generator widget on Pad 1.  The issue with data on the meter detail screen has been corrected, although the meter itself is still sending invalid data most of the time.

**Comment by susanbruno** [comment]
This is good stuff- I am sharing! Thank you,Su
